# Builds the user guide and lets the contributor know of
# any user guide build errors.
name: UserGuide CI

on:
  pull_request:
    paths:
      - 'user_guide_src/**'

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: user_guide_src
